import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import UserProvider from "@/context/UserProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black " >
      <UserProvider>
      <ToastContainer/>
            <div >
              <Header/>
            </div>
            <div className="mb-20" >
              {children}
            </div>
            <div >
              <Footer/>
            </div>
          </UserProvider>
          
        </body>
    </html>
  );
}
